const token = sessionStorage.getItem('noticeHubToken');
if (!token) window.location.href = 'login.html';
document.title = 'Files · CarePoint Pharmacy';
const files = [];
const fileInput = document.querySelector('#file-input');
const fileList = document.querySelector('#file-list');
const toast = document.querySelector('#toast');
function showToast(message) { toast.textContent = message; toast.classList.add('visible'); clearTimeout(showToast.timer); showToast.timer = setTimeout(() => toast.classList.remove('visible'), 2800); }
function renderFiles() { const query = document.querySelector('#file-search').value.toLowerCase(); const visible = files.filter((file) => file.name.toLowerCase().includes(query)); document.querySelector('#file-count').textContent = `${files.length} shared file${files.length === 1 ? '' : 's'}`; fileList.innerHTML = visible.map((file) => `<a class="full-file-row" href="${file.url || '#'}" ${file.url ? 'download' : ''}><span class="file-type ${file.className}">${file.type}</span><div class="file-info"><strong>${file.name}</strong><small>${file.meta}</small></div><i data-lucide="download"></i></a>`).join('') || '<div class="empty-state">No files match your search.</div>'; window.lucide?.createIcons(); }
async function loadFiles() { const response = await fetch('/api/files', { headers: { Authorization: `Bearer ${token}` } }); if (response.status === 401) return window.location.href = 'login.html'; files.splice(0, files.length, ...(await response.json())); renderFiles(); }
async function uploadFiles(selectedFiles) { if (!selectedFiles.length) return; const formData = new FormData(); selectedFiles.forEach((file) => formData.append('files', file)); const response = await fetch('/api/upload', { method: 'POST', headers: { Authorization: `Bearer ${token}` }, body: formData }); const data = await response.json(); if (!response.ok) return showToast(data.error); files.unshift(...data); renderFiles(); showToast(`${selectedFiles.length} file${selectedFiles.length > 1 ? 's' : ''} uploaded`); }
document.querySelector('#upload-files').addEventListener('click', () => fileInput.click()); document.querySelector('#drop-zone').addEventListener('click', () => fileInput.click()); fileInput.addEventListener('change', (event) => uploadFiles([...event.target.files])); document.querySelector('#file-search').addEventListener('input', renderFiles); document.querySelector('#drop-zone').addEventListener('dragover', (event) => { event.preventDefault(); event.currentTarget.classList.add('dragging'); }); document.querySelector('#drop-zone').addEventListener('dragleave', (event) => event.currentTarget.classList.remove('dragging')); document.querySelector('#drop-zone').addEventListener('drop', (event) => { event.preventDefault(); event.currentTarget.classList.remove('dragging'); uploadFiles([...event.dataTransfer.files]); });
loadFiles(); window.lucide?.createIcons();
